version: 2
updates:
  - package-ecosystem: "rust" # See documentation for possible values
    directory: "plain_implementations" # Location of package manifests
    schedule:
      interval: "weekly"
